/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.5.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDockWidget>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QToolBox>
#include <QtWidgets/QTreeWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionExit;
    QAction *actionOptions;
    QAction *actionRx_Config;
    QAction *actionRx_Control;
    QAction *actionFreq_Scanning;
    QAction *actionBookmark_Scanning;
    QWidget *centralWidget;
    QHBoxLayout *horizontalLayout;
    QToolBox *toolBox;
    QWidget *AirbandBookmarks;
    QTreeWidget *treeWidget_3;
    QWidget *Hambandsbooksmarks;
    QTreeWidget *treeWidget_2;
    QWidget *page;
    QTreeWidget *treeWidget_4;
    QWidget *page_2;
    QTreeWidget *treeWidget_5;
    QMenuBar *menuBar;
    QMenu *menuOptions;
    QMenu *menuWindows;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;
    QDockWidget *dockWidget_4;
    QWidget *dockWidgetContents_5;
    QTabWidget *tabWidget;
    QWidget *rx1;
    QLineEdit *lineEdit;
    QLabel *label;
    QLabel *label_2;
    QLineEdit *lineEdit_2;
    QLabel *label_3;
    QLineEdit *lineEdit_3;
    QWidget *rx2;
    QLineEdit *lineEdit_4;
    QLabel *label_4;
    QLabel *label_5;
    QLineEdit *lineEdit_5;
    QLabel *label_6;
    QLineEdit *lineEdit_6;
    QWidget *rx3;
    QLineEdit *lineEdit_7;
    QLabel *label_7;
    QLabel *label_8;
    QLineEdit *lineEdit_8;
    QLabel *label_9;
    QLineEdit *lineEdit_9;
    QDockWidget *dockWidget_5;
    QWidget *dockWidgetContents_6;
    QTabWidget *tabWidget_2;
    QWidget *rx1_3;
    QLineEdit *lineEdit_19;
    QLabel *label_19;
    QLabel *label_20;
    QLineEdit *lineEdit_20;
    QLabel *label_21;
    QLineEdit *lineEdit_21;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QPushButton *pushButton_3;
    QPushButton *pushButton_4;
    QPushButton *pushButton_5;
    QWidget *rx2_3;
    QPushButton *pushButton_11;
    QPushButton *pushButton_12;
    QPushButton *pushButton_13;
    QPushButton *pushButton_14;
    QLineEdit *lineEdit_22;
    QLabel *label_22;
    QPushButton *pushButton_15;
    QLineEdit *lineEdit_23;
    QLabel *label_23;
    QLabel *label_24;
    QLineEdit *lineEdit_24;
    QWidget *rx3_3;
    QPushButton *pushButton_16;
    QPushButton *pushButton_17;
    QPushButton *pushButton_18;
    QPushButton *pushButton_19;
    QLineEdit *lineEdit_25;
    QLabel *label_25;
    QPushButton *pushButton_20;
    QLineEdit *lineEdit_26;
    QLabel *label_26;
    QLabel *label_27;
    QLineEdit *lineEdit_27;
    QDockWidget *dockWidget_2;
    QWidget *dockWidgetContents_2;
    QLabel *label_55;
    QDoubleSpinBox *doubleSpinBox;
    QDoubleSpinBox *doubleSpinBox_2;
    QLabel *label_10;
    QLabel *label_11;
    QSpinBox *spinBox;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QComboBox *comboBox;
    QLabel *label_15;
    QRadioButton *radioButton;
    QPushButton *pushButton_6;
    QDockWidget *dockWidget_3;
    QWidget *dockWidgetContents_3;
    QLabel *label_56;
    QDoubleSpinBox *doubleSpinBox_3;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_28;
    QSpinBox *spinBox_2;
    QLabel *label_29;
    QLabel *label_30;
    QSpinBox *spinBox_3;
    QRadioButton *radioButton_2;
    QRadioButton *radioButton_3;
    QRadioButton *radioButton_4;
    QRadioButton *radioButton_5;
    QDockWidget *dockWidget_6;
    QWidget *dockWidgetContents_10;
    QLabel *label_57;
    QPushButton *pushButton_7;
    QPushButton *pushButton_8;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(850, 900);
        MainWindow->setMinimumSize(QSize(250, 250));
        MainWindow->setMaximumSize(QSize(850, 1600));
        MainWindow->setDockOptions(QMainWindow::AnimatedDocks|QMainWindow::VerticalTabs);
        MainWindow->setUnifiedTitleAndToolBarOnMac(false);
        actionExit = new QAction(MainWindow);
        actionExit->setObjectName(QStringLiteral("actionExit"));
        actionOptions = new QAction(MainWindow);
        actionOptions->setObjectName(QStringLiteral("actionOptions"));
        actionRx_Config = new QAction(MainWindow);
        actionRx_Config->setObjectName(QStringLiteral("actionRx_Config"));
        actionRx_Control = new QAction(MainWindow);
        actionRx_Control->setObjectName(QStringLiteral("actionRx_Control"));
        actionFreq_Scanning = new QAction(MainWindow);
        actionFreq_Scanning->setObjectName(QStringLiteral("actionFreq_Scanning"));
        actionBookmark_Scanning = new QAction(MainWindow);
        actionBookmark_Scanning->setObjectName(QStringLiteral("actionBookmark_Scanning"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        centralWidget->setMaximumSize(QSize(460, 676));
        horizontalLayout = new QHBoxLayout(centralWidget);
        horizontalLayout->setSpacing(0);
        horizontalLayout->setContentsMargins(11, 11, 11, 11);
        horizontalLayout->setObjectName(QStringLiteral("horizontalLayout"));
        horizontalLayout->setSizeConstraint(QLayout::SetMinimumSize);
        horizontalLayout->setContentsMargins(0, 0, 0, 0);
        toolBox = new QToolBox(centralWidget);
        toolBox->setObjectName(QStringLiteral("toolBox"));
        toolBox->setEnabled(true);
        toolBox->setMaximumSize(QSize(400, 1000));
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(114, 159, 207, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(196, 225, 255, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(155, 192, 231, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(57, 79, 103, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(76, 106, 138, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        QBrush brush6(QColor(255, 255, 255, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush7(QColor(184, 207, 231, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        QBrush brush8(QColor(255, 255, 220, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        toolBox->setPalette(palette);
        AirbandBookmarks = new QWidget();
        AirbandBookmarks->setObjectName(QStringLiteral("AirbandBookmarks"));
        AirbandBookmarks->setGeometry(QRect(0, 0, 400, 552));
        treeWidget_3 = new QTreeWidget(AirbandBookmarks);
        QTreeWidgetItem *__qtreewidgetitem = new QTreeWidgetItem(treeWidget_3);
        new QTreeWidgetItem(__qtreewidgetitem);
        new QTreeWidgetItem(__qtreewidgetitem);
        new QTreeWidgetItem(__qtreewidgetitem);
        QTreeWidgetItem *__qtreewidgetitem1 = new QTreeWidgetItem(treeWidget_3);
        new QTreeWidgetItem(__qtreewidgetitem1);
        new QTreeWidgetItem(__qtreewidgetitem1);
        treeWidget_3->setObjectName(QStringLiteral("treeWidget_3"));
        treeWidget_3->setGeometry(QRect(0, 0, 400, 551));
        treeWidget_3->setDragEnabled(true);
        treeWidget_3->setDragDropMode(QAbstractItemView::DragDrop);
        treeWidget_3->setAlternatingRowColors(true);
        treeWidget_3->setSortingEnabled(true);
        treeWidget_3->setAnimated(true);
        toolBox->addItem(AirbandBookmarks, QStringLiteral("Airband Bookmarks"));
        Hambandsbooksmarks = new QWidget();
        Hambandsbooksmarks->setObjectName(QStringLiteral("Hambandsbooksmarks"));
        Hambandsbooksmarks->setGeometry(QRect(0, 0, 400, 552));
        treeWidget_2 = new QTreeWidget(Hambandsbooksmarks);
        QTreeWidgetItem *__qtreewidgetitem2 = new QTreeWidgetItem(treeWidget_2);
        new QTreeWidgetItem(__qtreewidgetitem2);
        new QTreeWidgetItem(__qtreewidgetitem2);
        new QTreeWidgetItem(__qtreewidgetitem2);
        QTreeWidgetItem *__qtreewidgetitem3 = new QTreeWidgetItem(treeWidget_2);
        new QTreeWidgetItem(__qtreewidgetitem3);
        new QTreeWidgetItem(__qtreewidgetitem3);
        treeWidget_2->setObjectName(QStringLiteral("treeWidget_2"));
        treeWidget_2->setGeometry(QRect(0, 0, 400, 551));
        treeWidget_2->setDragEnabled(true);
        treeWidget_2->setDragDropMode(QAbstractItemView::DragDrop);
        treeWidget_2->setAlternatingRowColors(true);
        treeWidget_2->setSortingEnabled(true);
        treeWidget_2->setAnimated(true);
        toolBox->addItem(Hambandsbooksmarks, QStringLiteral("Ham band Bookmarks"));
        page = new QWidget();
        page->setObjectName(QStringLiteral("page"));
        page->setGeometry(QRect(0, 0, 400, 552));
        treeWidget_4 = new QTreeWidget(page);
        QTreeWidgetItem *__qtreewidgetitem4 = new QTreeWidgetItem(treeWidget_4);
        new QTreeWidgetItem(__qtreewidgetitem4);
        new QTreeWidgetItem(__qtreewidgetitem4);
        new QTreeWidgetItem(__qtreewidgetitem4);
        QTreeWidgetItem *__qtreewidgetitem5 = new QTreeWidgetItem(treeWidget_4);
        new QTreeWidgetItem(__qtreewidgetitem5);
        new QTreeWidgetItem(__qtreewidgetitem5);
        treeWidget_4->setObjectName(QStringLiteral("treeWidget_4"));
        treeWidget_4->setGeometry(QRect(0, 0, 400, 551));
        treeWidget_4->setDragEnabled(true);
        treeWidget_4->setDragDropMode(QAbstractItemView::DragDrop);
        treeWidget_4->setAlternatingRowColors(true);
        treeWidget_4->setSortingEnabled(true);
        treeWidget_4->setAnimated(true);
        toolBox->addItem(page, QStringLiteral("Marine Bookmarks"));
        page_2 = new QWidget();
        page_2->setObjectName(QStringLiteral("page_2"));
        page_2->setGeometry(QRect(0, 0, 400, 552));
        treeWidget_5 = new QTreeWidget(page_2);
        QTreeWidgetItem *__qtreewidgetitem6 = new QTreeWidgetItem(treeWidget_5);
        new QTreeWidgetItem(__qtreewidgetitem6);
        new QTreeWidgetItem(__qtreewidgetitem6);
        new QTreeWidgetItem(__qtreewidgetitem6);
        QTreeWidgetItem *__qtreewidgetitem7 = new QTreeWidgetItem(treeWidget_5);
        new QTreeWidgetItem(__qtreewidgetitem7);
        new QTreeWidgetItem(__qtreewidgetitem7);
        treeWidget_5->setObjectName(QStringLiteral("treeWidget_5"));
        treeWidget_5->setGeometry(QRect(0, 0, 400, 551));
        treeWidget_5->setDragEnabled(true);
        treeWidget_5->setDragDropMode(QAbstractItemView::DragDrop);
        treeWidget_5->setAlternatingRowColors(true);
        treeWidget_5->setSortingEnabled(true);
        treeWidget_5->setAnimated(true);
        toolBox->addItem(page_2, QStringLiteral("NDB Bookmarks"));

        horizontalLayout->addWidget(toolBox);

        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 850, 22));
        menuOptions = new QMenu(menuBar);
        menuOptions->setObjectName(QStringLiteral("menuOptions"));
        menuWindows = new QMenu(menuBar);
        menuWindows->setObjectName(QStringLiteral("menuWindows"));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);
        dockWidget_4 = new QDockWidget(MainWindow);
        dockWidget_4->setObjectName(QStringLiteral("dockWidget_4"));
        dockWidget_4->setMaximumSize(QSize(320, 200));
        dockWidget_4->setBaseSize(QSize(100, 100));
        dockWidget_4->setFloating(false);
        dockWidget_4->setAllowedAreas(Qt::RightDockWidgetArea);
        dockWidgetContents_5 = new QWidget();
        dockWidgetContents_5->setObjectName(QStringLiteral("dockWidgetContents_5"));
        dockWidgetContents_5->setMaximumSize(QSize(350, 200));
        tabWidget = new QTabWidget(dockWidgetContents_5);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(0, 0, 271, 121));
        rx1 = new QWidget();
        rx1->setObjectName(QStringLiteral("rx1"));
        lineEdit = new QLineEdit(rx1);
        lineEdit->setObjectName(QStringLiteral("lineEdit"));
        lineEdit->setGeometry(QRect(120, 31, 113, 25));
        lineEdit->setMaxLength(15);
        label = new QLabel(rx1);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(10, 35, 101, 17));
        label_2 = new QLabel(rx1);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 65, 101, 17));
        lineEdit_2 = new QLineEdit(rx1);
        lineEdit_2->setObjectName(QStringLiteral("lineEdit_2"));
        lineEdit_2->setGeometry(QRect(120, 61, 41, 25));
        lineEdit_2->setMaxLength(5);
        label_3 = new QLabel(rx1);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(10, 4, 101, 17));
        lineEdit_3 = new QLineEdit(rx1);
        lineEdit_3->setObjectName(QStringLiteral("lineEdit_3"));
        lineEdit_3->setGeometry(QRect(120, 0, 113, 25));
        lineEdit_3->setMaxLength(32767);
        tabWidget->addTab(rx1, QString());
        rx2 = new QWidget();
        rx2->setObjectName(QStringLiteral("rx2"));
        lineEdit_4 = new QLineEdit(rx2);
        lineEdit_4->setObjectName(QStringLiteral("lineEdit_4"));
        lineEdit_4->setGeometry(QRect(120, 31, 113, 25));
        lineEdit_4->setMaxLength(15);
        label_4 = new QLabel(rx2);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(10, 35, 101, 17));
        label_5 = new QLabel(rx2);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(10, 65, 101, 17));
        lineEdit_5 = new QLineEdit(rx2);
        lineEdit_5->setObjectName(QStringLiteral("lineEdit_5"));
        lineEdit_5->setGeometry(QRect(120, 61, 41, 25));
        lineEdit_5->setMaxLength(5);
        label_6 = new QLabel(rx2);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(10, 4, 101, 17));
        lineEdit_6 = new QLineEdit(rx2);
        lineEdit_6->setObjectName(QStringLiteral("lineEdit_6"));
        lineEdit_6->setGeometry(QRect(120, 0, 113, 25));
        lineEdit_6->setMaxLength(32767);
        tabWidget->addTab(rx2, QString());
        rx3 = new QWidget();
        rx3->setObjectName(QStringLiteral("rx3"));
        lineEdit_7 = new QLineEdit(rx3);
        lineEdit_7->setObjectName(QStringLiteral("lineEdit_7"));
        lineEdit_7->setGeometry(QRect(120, 31, 113, 25));
        lineEdit_7->setMaxLength(15);
        label_7 = new QLabel(rx3);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(10, 35, 101, 17));
        label_8 = new QLabel(rx3);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(10, 65, 101, 17));
        lineEdit_8 = new QLineEdit(rx3);
        lineEdit_8->setObjectName(QStringLiteral("lineEdit_8"));
        lineEdit_8->setGeometry(QRect(120, 61, 41, 25));
        lineEdit_8->setMaxLength(5);
        label_9 = new QLabel(rx3);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(10, 4, 101, 17));
        lineEdit_9 = new QLineEdit(rx3);
        lineEdit_9->setObjectName(QStringLiteral("lineEdit_9"));
        lineEdit_9->setGeometry(QRect(120, 0, 113, 25));
        lineEdit_9->setMaxLength(32767);
        tabWidget->addTab(rx3, QString());
        dockWidget_4->setWidget(dockWidgetContents_5);
        MainWindow->addDockWidget(static_cast<Qt::DockWidgetArea>(2), dockWidget_4);
        dockWidget_5 = new QDockWidget(MainWindow);
        dockWidget_5->setObjectName(QStringLiteral("dockWidget_5"));
        dockWidget_5->setMaximumSize(QSize(320, 200));
        dockWidget_5->setFloating(false);
        dockWidget_5->setAllowedAreas(Qt::RightDockWidgetArea);
        dockWidgetContents_6 = new QWidget();
        dockWidgetContents_6->setObjectName(QStringLiteral("dockWidgetContents_6"));
        dockWidgetContents_6->setMaximumSize(QSize(350, 200));
        tabWidget_2 = new QTabWidget(dockWidgetContents_6);
        tabWidget_2->setObjectName(QStringLiteral("tabWidget_2"));
        tabWidget_2->setGeometry(QRect(0, 0, 271, 121));
        rx1_3 = new QWidget();
        rx1_3->setObjectName(QStringLiteral("rx1_3"));
        lineEdit_19 = new QLineEdit(rx1_3);
        lineEdit_19->setObjectName(QStringLiteral("lineEdit_19"));
        lineEdit_19->setGeometry(QRect(120, 35, 71, 25));
        lineEdit_19->setMaxLength(32767);
        label_19 = new QLabel(rx1_3);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(10, 39, 101, 17));
        label_20 = new QLabel(rx1_3);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(10, 69, 101, 17));
        lineEdit_20 = new QLineEdit(rx1_3);
        lineEdit_20->setObjectName(QStringLiteral("lineEdit_20"));
        lineEdit_20->setGeometry(QRect(120, 65, 111, 25));
        lineEdit_20->setMaxLength(32767);
        label_21 = new QLabel(rx1_3);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(10, 8, 101, 17));
        lineEdit_21 = new QLineEdit(rx1_3);
        lineEdit_21->setObjectName(QStringLiteral("lineEdit_21"));
        lineEdit_21->setGeometry(QRect(120, 4, 113, 25));
        lineEdit_21->setMaxLength(11);
        pushButton = new QPushButton(rx1_3);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(0, 104, 80, 25));
        pushButton_2 = new QPushButton(rx1_3);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(80, 104, 80, 25));
        pushButton_3 = new QPushButton(rx1_3);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(160, 104, 80, 25));
        pushButton_4 = new QPushButton(rx1_3);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(40, 134, 80, 25));
        pushButton_5 = new QPushButton(rx1_3);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(130, 134, 80, 25));
        tabWidget_2->addTab(rx1_3, QString());
        rx2_3 = new QWidget();
        rx2_3->setObjectName(QStringLiteral("rx2_3"));
        pushButton_11 = new QPushButton(rx2_3);
        pushButton_11->setObjectName(QStringLiteral("pushButton_11"));
        pushButton_11->setGeometry(QRect(80, 109, 80, 25));
        pushButton_12 = new QPushButton(rx2_3);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));
        pushButton_12->setGeometry(QRect(160, 109, 80, 25));
        pushButton_13 = new QPushButton(rx2_3);
        pushButton_13->setObjectName(QStringLiteral("pushButton_13"));
        pushButton_13->setGeometry(QRect(130, 139, 80, 25));
        pushButton_14 = new QPushButton(rx2_3);
        pushButton_14->setObjectName(QStringLiteral("pushButton_14"));
        pushButton_14->setGeometry(QRect(0, 109, 80, 25));
        lineEdit_22 = new QLineEdit(rx2_3);
        lineEdit_22->setObjectName(QStringLiteral("lineEdit_22"));
        lineEdit_22->setGeometry(QRect(120, 9, 113, 25));
        lineEdit_22->setMaxLength(11);
        label_22 = new QLabel(rx2_3);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(10, 44, 101, 17));
        pushButton_15 = new QPushButton(rx2_3);
        pushButton_15->setObjectName(QStringLiteral("pushButton_15"));
        pushButton_15->setGeometry(QRect(40, 139, 80, 25));
        lineEdit_23 = new QLineEdit(rx2_3);
        lineEdit_23->setObjectName(QStringLiteral("lineEdit_23"));
        lineEdit_23->setGeometry(QRect(120, 70, 111, 25));
        lineEdit_23->setMaxLength(32767);
        label_23 = new QLabel(rx2_3);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(10, 74, 101, 17));
        label_24 = new QLabel(rx2_3);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(10, 13, 101, 17));
        lineEdit_24 = new QLineEdit(rx2_3);
        lineEdit_24->setObjectName(QStringLiteral("lineEdit_24"));
        lineEdit_24->setGeometry(QRect(120, 40, 71, 25));
        lineEdit_24->setMaxLength(32767);
        tabWidget_2->addTab(rx2_3, QString());
        rx3_3 = new QWidget();
        rx3_3->setObjectName(QStringLiteral("rx3_3"));
        pushButton_16 = new QPushButton(rx3_3);
        pushButton_16->setObjectName(QStringLiteral("pushButton_16"));
        pushButton_16->setGeometry(QRect(80, 109, 80, 25));
        pushButton_17 = new QPushButton(rx3_3);
        pushButton_17->setObjectName(QStringLiteral("pushButton_17"));
        pushButton_17->setGeometry(QRect(160, 109, 80, 25));
        pushButton_18 = new QPushButton(rx3_3);
        pushButton_18->setObjectName(QStringLiteral("pushButton_18"));
        pushButton_18->setGeometry(QRect(130, 139, 80, 25));
        pushButton_19 = new QPushButton(rx3_3);
        pushButton_19->setObjectName(QStringLiteral("pushButton_19"));
        pushButton_19->setGeometry(QRect(0, 109, 80, 25));
        lineEdit_25 = new QLineEdit(rx3_3);
        lineEdit_25->setObjectName(QStringLiteral("lineEdit_25"));
        lineEdit_25->setGeometry(QRect(120, 9, 113, 25));
        lineEdit_25->setMaxLength(11);
        label_25 = new QLabel(rx3_3);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(10, 44, 101, 17));
        pushButton_20 = new QPushButton(rx3_3);
        pushButton_20->setObjectName(QStringLiteral("pushButton_20"));
        pushButton_20->setGeometry(QRect(40, 139, 80, 25));
        lineEdit_26 = new QLineEdit(rx3_3);
        lineEdit_26->setObjectName(QStringLiteral("lineEdit_26"));
        lineEdit_26->setGeometry(QRect(120, 70, 111, 25));
        lineEdit_26->setMaxLength(32767);
        label_26 = new QLabel(rx3_3);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(10, 74, 101, 17));
        label_27 = new QLabel(rx3_3);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(10, 13, 101, 17));
        lineEdit_27 = new QLineEdit(rx3_3);
        lineEdit_27->setObjectName(QStringLiteral("lineEdit_27"));
        lineEdit_27->setGeometry(QRect(120, 40, 71, 25));
        lineEdit_27->setMaxLength(32767);
        tabWidget_2->addTab(rx3_3, QString());
        dockWidget_5->setWidget(dockWidgetContents_6);
        MainWindow->addDockWidget(static_cast<Qt::DockWidgetArea>(2), dockWidget_5);
        dockWidget_2 = new QDockWidget(MainWindow);
        dockWidget_2->setObjectName(QStringLiteral("dockWidget_2"));
        dockWidget_2->setMaximumSize(QSize(320, 200));
        dockWidget_2->setAllowedAreas(Qt::RightDockWidgetArea);
        dockWidgetContents_2 = new QWidget();
        dockWidgetContents_2->setObjectName(QStringLiteral("dockWidgetContents_2"));
        dockWidgetContents_2->setMaximumSize(QSize(16777215, 200));
        label_55 = new QLabel(dockWidgetContents_2);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(10, 10, 121, 17));
        doubleSpinBox = new QDoubleSpinBox(dockWidgetContents_2);
        doubleSpinBox->setObjectName(QStringLiteral("doubleSpinBox"));
        doubleSpinBox->setGeometry(QRect(40, 30, 62, 26));
        doubleSpinBox->setDecimals(3);
        doubleSpinBox->setMaximum(1e+09);
        doubleSpinBox->setSingleStep(0.001);
        doubleSpinBox_2 = new QDoubleSpinBox(dockWidgetContents_2);
        doubleSpinBox_2->setObjectName(QStringLiteral("doubleSpinBox_2"));
        doubleSpinBox_2->setGeometry(QRect(150, 30, 62, 26));
        doubleSpinBox_2->setWrapping(true);
        doubleSpinBox_2->setDecimals(3);
        doubleSpinBox_2->setMaximum(1e+09);
        doubleSpinBox_2->setSingleStep(0.001);
        label_10 = new QLabel(dockWidgetContents_2);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(10, 34, 31, 16));
        label_11 = new QLabel(dockWidgetContents_2);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(120, 34, 31, 16));
        spinBox = new QSpinBox(dockWidgetContents_2);
        spinBox->setObjectName(QStringLiteral("spinBox"));
        spinBox->setGeometry(QRect(70, 60, 45, 26));
        label_12 = new QLabel(dockWidgetContents_2);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(11, 64, 51, 16));
        label_13 = new QLabel(dockWidgetContents_2);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(120, 62, 31, 16));
        label_14 = new QLabel(dockWidgetContents_2);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(220, 33, 31, 16));
        comboBox = new QComboBox(dockWidgetContents_2);
        comboBox->setObjectName(QStringLiteral("comboBox"));
        comboBox->setGeometry(QRect(220, 60, 81, 21));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush9(QColor(138, 226, 52, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush9);
        QBrush brush10(QColor(198, 255, 143, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush10);
        QBrush brush11(QColor(168, 240, 97, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush11);
        QBrush brush12(QColor(69, 113, 26, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush12);
        QBrush brush13(QColor(92, 151, 34, 255));
        brush13.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush13);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush9);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush14(QColor(196, 240, 153, 255));
        brush14.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush14);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush9);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush10);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush11);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush12);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush13);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush9);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush14);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush9);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush10);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush11);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush12);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush13);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush9);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush9);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush9);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        comboBox->setPalette(palette1);
        comboBox->setFocusPolicy(Qt::TabFocus);
        comboBox->setEditable(false);
        label_15 = new QLabel(dockWidgetContents_2);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(150, 62, 71, 16));
        radioButton = new QRadioButton(dockWidgetContents_2);
        radioButton->setObjectName(QStringLiteral("radioButton"));
        radioButton->setGeometry(QRect(30, 90, 131, 23));
        pushButton_6 = new QPushButton(dockWidgetContents_2);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(240, 90, 80, 25));
        dockWidget_2->setWidget(dockWidgetContents_2);
        MainWindow->addDockWidget(static_cast<Qt::DockWidgetArea>(2), dockWidget_2);
        dockWidget_3 = new QDockWidget(MainWindow);
        dockWidget_3->setObjectName(QStringLiteral("dockWidget_3"));
        dockWidget_3->setMaximumSize(QSize(320, 200));
        dockWidget_3->setAllowedAreas(Qt::RightDockWidgetArea);
        dockWidgetContents_3 = new QWidget();
        dockWidgetContents_3->setObjectName(QStringLiteral("dockWidgetContents_3"));
        dockWidgetContents_3->setMaximumSize(QSize(330, 200));
        label_56 = new QLabel(dockWidgetContents_3);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(10, 0, 111, 17));
        doubleSpinBox_3 = new QDoubleSpinBox(dockWidgetContents_3);
        doubleSpinBox_3->setObjectName(QStringLiteral("doubleSpinBox_3"));
        doubleSpinBox_3->setGeometry(QRect(100, 20, 62, 26));
        doubleSpinBox_3->setDecimals(3);
        doubleSpinBox_3->setMaximum(1e+09);
        doubleSpinBox_3->setSingleStep(0.001);
        label_16 = new QLabel(dockWidgetContents_3);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(20, 25, 81, 16));
        label_17 = new QLabel(dockWidgetContents_3);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(170, 25, 31, 16));
        label_18 = new QLabel(dockWidgetContents_3);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(170, 53, 51, 16));
        label_28 = new QLabel(dockWidgetContents_3);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(20, 52, 81, 16));
        spinBox_2 = new QSpinBox(dockWidgetContents_3);
        spinBox_2->setObjectName(QStringLiteral("spinBox_2"));
        spinBox_2->setGeometry(QRect(104, 50, 51, 26));
        label_29 = new QLabel(dockWidgetContents_3);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(170, 83, 71, 16));
        label_30 = new QLabel(dockWidgetContents_3);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(20, 82, 81, 16));
        spinBox_3 = new QSpinBox(dockWidgetContents_3);
        spinBox_3->setObjectName(QStringLiteral("spinBox_3"));
        spinBox_3->setGeometry(QRect(104, 80, 51, 26));
        radioButton_2 = new QRadioButton(dockWidgetContents_3);
        radioButton_2->setObjectName(QStringLiteral("radioButton_2"));
        radioButton_2->setGeometry(QRect(20, 110, 61, 23));
        radioButton_3 = new QRadioButton(dockWidgetContents_3);
        radioButton_3->setObjectName(QStringLiteral("radioButton_3"));
        radioButton_3->setGeometry(QRect(80, 110, 61, 23));
        radioButton_4 = new QRadioButton(dockWidgetContents_3);
        radioButton_4->setObjectName(QStringLiteral("radioButton_4"));
        radioButton_4->setGeometry(QRect(150, 110, 61, 23));
        radioButton_5 = new QRadioButton(dockWidgetContents_3);
        radioButton_5->setObjectName(QStringLiteral("radioButton_5"));
        radioButton_5->setGeometry(QRect(210, 110, 61, 23));
        dockWidget_3->setWidget(dockWidgetContents_3);
        MainWindow->addDockWidget(static_cast<Qt::DockWidgetArea>(2), dockWidget_3);
        dockWidget_6 = new QDockWidget(MainWindow);
        dockWidget_6->setObjectName(QStringLiteral("dockWidget_6"));
        dockWidget_6->setMaximumSize(QSize(320, 200));
        dockWidget_6->setAllowedAreas(Qt::RightDockWidgetArea);
        dockWidgetContents_10 = new QWidget();
        dockWidgetContents_10->setObjectName(QStringLiteral("dockWidgetContents_10"));
        dockWidgetContents_10->setMaximumSize(QSize(320, 200));
        label_57 = new QLabel(dockWidgetContents_10);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(10, 0, 131, 17));
        pushButton_7 = new QPushButton(dockWidgetContents_10);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(30, 20, 80, 25));
        pushButton_8 = new QPushButton(dockWidgetContents_10);
        pushButton_8->setObjectName(QStringLiteral("pushButton_8"));
        pushButton_8->setGeometry(QRect(130, 20, 80, 25));
        dockWidget_6->setWidget(dockWidgetContents_10);
        MainWindow->addDockWidget(static_cast<Qt::DockWidgetArea>(2), dockWidget_6);

        menuBar->addAction(menuOptions->menuAction());
        menuBar->addAction(menuWindows->menuAction());
        menuOptions->addAction(actionOptions);
        menuOptions->addAction(actionExit);
        menuWindows->addAction(actionRx_Config);
        menuWindows->addAction(actionRx_Control);
        menuWindows->addAction(actionFreq_Scanning);
        menuWindows->addAction(actionBookmark_Scanning);

        retranslateUi(MainWindow);

        toolBox->setCurrentIndex(0);
        tabWidget->setCurrentIndex(1);
        tabWidget_2->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "Rig Remote", 0));
        actionExit->setText(QApplication::translate("MainWindow", "Exit", 0));
        actionOptions->setText(QApplication::translate("MainWindow", "Options", 0));
        actionRx_Config->setText(QApplication::translate("MainWindow", "Rx Config", 0));
        actionRx_Control->setText(QApplication::translate("MainWindow", "Rx Control", 0));
        actionFreq_Scanning->setText(QApplication::translate("MainWindow", "Freq Scanning", 0));
        actionBookmark_Scanning->setText(QApplication::translate("MainWindow", "Bookmark Scanning", 0));
        QTreeWidgetItem *___qtreewidgetitem = treeWidget_3->headerItem();
        ___qtreewidgetitem->setText(3, QApplication::translate("MainWindow", "Mode", 0));
        ___qtreewidgetitem->setText(2, QApplication::translate("MainWindow", "Frequency", 0));
        ___qtreewidgetitem->setText(1, QApplication::translate("MainWindow", "Name", 0));
        ___qtreewidgetitem->setText(0, QApplication::translate("MainWindow", "1", 0));

        const bool __sortingEnabled = treeWidget_3->isSortingEnabled();
        treeWidget_3->setSortingEnabled(false);
        QTreeWidgetItem *___qtreewidgetitem1 = treeWidget_3->topLevelItem(0);
        ___qtreewidgetitem1->setText(1, QApplication::translate("MainWindow", "LGW", 0));
        ___qtreewidgetitem1->setText(0, QApplication::translate("MainWindow", "2", 0));
        QTreeWidgetItem *___qtreewidgetitem2 = ___qtreewidgetitem1->child(0);
        ___qtreewidgetitem2->setText(3, QApplication::translate("MainWindow", "AM", 0));
        ___qtreewidgetitem2->setText(2, QApplication::translate("MainWindow", "130.100", 0));
        ___qtreewidgetitem2->setText(1, QApplication::translate("MainWindow", "LGW ATIS", 0));
        ___qtreewidgetitem2->setText(0, QApplication::translate("MainWindow", "2.3", 0));
        QTreeWidgetItem *___qtreewidgetitem3 = ___qtreewidgetitem1->child(1);
        ___qtreewidgetitem3->setText(3, QApplication::translate("MainWindow", "AM", 0));
        ___qtreewidgetitem3->setText(2, QApplication::translate("MainWindow", "123.789", 0));
        ___qtreewidgetitem3->setText(1, QApplication::translate("MainWindow", "LGW Departures", 0));
        ___qtreewidgetitem3->setText(0, QApplication::translate("MainWindow", "2.2", 0));
        QTreeWidgetItem *___qtreewidgetitem4 = ___qtreewidgetitem1->child(2);
        ___qtreewidgetitem4->setText(3, QApplication::translate("MainWindow", "AM", 0));
        ___qtreewidgetitem4->setText(2, QApplication::translate("MainWindow", "121.600", 0));
        ___qtreewidgetitem4->setText(1, QApplication::translate("MainWindow", "LGW Tower", 0));
        ___qtreewidgetitem4->setText(0, QApplication::translate("MainWindow", "2.1", 0));
        QTreeWidgetItem *___qtreewidgetitem5 = treeWidget_3->topLevelItem(1);
        ___qtreewidgetitem5->setText(1, QApplication::translate("MainWindow", "LHR", 0));
        ___qtreewidgetitem5->setText(0, QApplication::translate("MainWindow", "1", 0));
        QTreeWidgetItem *___qtreewidgetitem6 = ___qtreewidgetitem5->child(0);
        ___qtreewidgetitem6->setText(3, QApplication::translate("MainWindow", "AM", 0));
        ___qtreewidgetitem6->setText(2, QApplication::translate("MainWindow", "120.450", 0));
        ___qtreewidgetitem6->setText(1, QApplication::translate("MainWindow", "LHR Approach", 0));
        ___qtreewidgetitem6->setText(0, QApplication::translate("MainWindow", "1.2", 0));
        QTreeWidgetItem *___qtreewidgetitem7 = ___qtreewidgetitem5->child(1);
        ___qtreewidgetitem7->setText(3, QApplication::translate("MainWindow", "AM", 0));
        ___qtreewidgetitem7->setText(2, QApplication::translate("MainWindow", "118.345", 0));
        ___qtreewidgetitem7->setText(1, QApplication::translate("MainWindow", "LHR Tower", 0));
        ___qtreewidgetitem7->setText(0, QApplication::translate("MainWindow", "1.1", 0));
        treeWidget_3->setSortingEnabled(__sortingEnabled);

        toolBox->setItemText(toolBox->indexOf(AirbandBookmarks), QApplication::translate("MainWindow", "Airband Bookmarks", 0));
        QTreeWidgetItem *___qtreewidgetitem8 = treeWidget_2->headerItem();
        ___qtreewidgetitem8->setText(3, QApplication::translate("MainWindow", "Mode", 0));
        ___qtreewidgetitem8->setText(2, QApplication::translate("MainWindow", "Frequency", 0));
        ___qtreewidgetitem8->setText(1, QApplication::translate("MainWindow", "Name", 0));
        ___qtreewidgetitem8->setText(0, QApplication::translate("MainWindow", "1", 0));

        const bool __sortingEnabled1 = treeWidget_2->isSortingEnabled();
        treeWidget_2->setSortingEnabled(false);
        QTreeWidgetItem *___qtreewidgetitem9 = treeWidget_2->topLevelItem(0);
        ___qtreewidgetitem9->setText(1, QApplication::translate("MainWindow", "LGW", 0));
        ___qtreewidgetitem9->setText(0, QApplication::translate("MainWindow", "2", 0));
        QTreeWidgetItem *___qtreewidgetitem10 = ___qtreewidgetitem9->child(0);
        ___qtreewidgetitem10->setText(3, QApplication::translate("MainWindow", "AM", 0));
        ___qtreewidgetitem10->setText(2, QApplication::translate("MainWindow", "130.100", 0));
        ___qtreewidgetitem10->setText(1, QApplication::translate("MainWindow", "LGW ATIS", 0));
        ___qtreewidgetitem10->setText(0, QApplication::translate("MainWindow", "2.3", 0));
        QTreeWidgetItem *___qtreewidgetitem11 = ___qtreewidgetitem9->child(1);
        ___qtreewidgetitem11->setText(3, QApplication::translate("MainWindow", "AM", 0));
        ___qtreewidgetitem11->setText(2, QApplication::translate("MainWindow", "123.789", 0));
        ___qtreewidgetitem11->setText(1, QApplication::translate("MainWindow", "LGW Departures", 0));
        ___qtreewidgetitem11->setText(0, QApplication::translate("MainWindow", "2.2", 0));
        QTreeWidgetItem *___qtreewidgetitem12 = ___qtreewidgetitem9->child(2);
        ___qtreewidgetitem12->setText(3, QApplication::translate("MainWindow", "AM", 0));
        ___qtreewidgetitem12->setText(2, QApplication::translate("MainWindow", "121.600", 0));
        ___qtreewidgetitem12->setText(1, QApplication::translate("MainWindow", "LGW Tower", 0));
        ___qtreewidgetitem12->setText(0, QApplication::translate("MainWindow", "2.1", 0));
        QTreeWidgetItem *___qtreewidgetitem13 = treeWidget_2->topLevelItem(1);
        ___qtreewidgetitem13->setText(1, QApplication::translate("MainWindow", "LHR", 0));
        ___qtreewidgetitem13->setText(0, QApplication::translate("MainWindow", "1", 0));
        QTreeWidgetItem *___qtreewidgetitem14 = ___qtreewidgetitem13->child(0);
        ___qtreewidgetitem14->setText(3, QApplication::translate("MainWindow", "AM", 0));
        ___qtreewidgetitem14->setText(2, QApplication::translate("MainWindow", "120.450", 0));
        ___qtreewidgetitem14->setText(1, QApplication::translate("MainWindow", "LHR Approach", 0));
        ___qtreewidgetitem14->setText(0, QApplication::translate("MainWindow", "1.2", 0));
        QTreeWidgetItem *___qtreewidgetitem15 = ___qtreewidgetitem13->child(1);
        ___qtreewidgetitem15->setText(3, QApplication::translate("MainWindow", "AM", 0));
        ___qtreewidgetitem15->setText(2, QApplication::translate("MainWindow", "118.345", 0));
        ___qtreewidgetitem15->setText(1, QApplication::translate("MainWindow", "LHR Tower", 0));
        ___qtreewidgetitem15->setText(0, QApplication::translate("MainWindow", "1.1", 0));
        treeWidget_2->setSortingEnabled(__sortingEnabled1);

        toolBox->setItemText(toolBox->indexOf(Hambandsbooksmarks), QApplication::translate("MainWindow", "Ham band Bookmarks", 0));
        QTreeWidgetItem *___qtreewidgetitem16 = treeWidget_4->headerItem();
        ___qtreewidgetitem16->setText(3, QApplication::translate("MainWindow", "Mode", 0));
        ___qtreewidgetitem16->setText(2, QApplication::translate("MainWindow", "Frequency", 0));
        ___qtreewidgetitem16->setText(1, QApplication::translate("MainWindow", "Name", 0));
        ___qtreewidgetitem16->setText(0, QApplication::translate("MainWindow", "1", 0));

        const bool __sortingEnabled2 = treeWidget_4->isSortingEnabled();
        treeWidget_4->setSortingEnabled(false);
        QTreeWidgetItem *___qtreewidgetitem17 = treeWidget_4->topLevelItem(0);
        ___qtreewidgetitem17->setText(1, QApplication::translate("MainWindow", "LGW", 0));
        ___qtreewidgetitem17->setText(0, QApplication::translate("MainWindow", "2", 0));
        QTreeWidgetItem *___qtreewidgetitem18 = ___qtreewidgetitem17->child(0);
        ___qtreewidgetitem18->setText(3, QApplication::translate("MainWindow", "AM", 0));
        ___qtreewidgetitem18->setText(2, QApplication::translate("MainWindow", "130.100", 0));
        ___qtreewidgetitem18->setText(1, QApplication::translate("MainWindow", "LGW ATIS", 0));
        ___qtreewidgetitem18->setText(0, QApplication::translate("MainWindow", "2.3", 0));
        QTreeWidgetItem *___qtreewidgetitem19 = ___qtreewidgetitem17->child(1);
        ___qtreewidgetitem19->setText(3, QApplication::translate("MainWindow", "AM", 0));
        ___qtreewidgetitem19->setText(2, QApplication::translate("MainWindow", "123.789", 0));
        ___qtreewidgetitem19->setText(1, QApplication::translate("MainWindow", "LGW Departures", 0));
        ___qtreewidgetitem19->setText(0, QApplication::translate("MainWindow", "2.2", 0));
        QTreeWidgetItem *___qtreewidgetitem20 = ___qtreewidgetitem17->child(2);
        ___qtreewidgetitem20->setText(3, QApplication::translate("MainWindow", "AM", 0));
        ___qtreewidgetitem20->setText(2, QApplication::translate("MainWindow", "121.600", 0));
        ___qtreewidgetitem20->setText(1, QApplication::translate("MainWindow", "LGW Tower", 0));
        ___qtreewidgetitem20->setText(0, QApplication::translate("MainWindow", "2.1", 0));
        QTreeWidgetItem *___qtreewidgetitem21 = treeWidget_4->topLevelItem(1);
        ___qtreewidgetitem21->setText(1, QApplication::translate("MainWindow", "LHR", 0));
        ___qtreewidgetitem21->setText(0, QApplication::translate("MainWindow", "1", 0));
        QTreeWidgetItem *___qtreewidgetitem22 = ___qtreewidgetitem21->child(0);
        ___qtreewidgetitem22->setText(3, QApplication::translate("MainWindow", "AM", 0));
        ___qtreewidgetitem22->setText(2, QApplication::translate("MainWindow", "120.450", 0));
        ___qtreewidgetitem22->setText(1, QApplication::translate("MainWindow", "LHR Approach", 0));
        ___qtreewidgetitem22->setText(0, QApplication::translate("MainWindow", "1.2", 0));
        QTreeWidgetItem *___qtreewidgetitem23 = ___qtreewidgetitem21->child(1);
        ___qtreewidgetitem23->setText(3, QApplication::translate("MainWindow", "AM", 0));
        ___qtreewidgetitem23->setText(2, QApplication::translate("MainWindow", "118.345", 0));
        ___qtreewidgetitem23->setText(1, QApplication::translate("MainWindow", "LHR Tower", 0));
        ___qtreewidgetitem23->setText(0, QApplication::translate("MainWindow", "1.1", 0));
        treeWidget_4->setSortingEnabled(__sortingEnabled2);

        toolBox->setItemText(toolBox->indexOf(page), QApplication::translate("MainWindow", "Marine Bookmarks", 0));
        QTreeWidgetItem *___qtreewidgetitem24 = treeWidget_5->headerItem();
        ___qtreewidgetitem24->setText(3, QApplication::translate("MainWindow", "Mode", 0));
        ___qtreewidgetitem24->setText(2, QApplication::translate("MainWindow", "Frequency", 0));
        ___qtreewidgetitem24->setText(1, QApplication::translate("MainWindow", "Name", 0));
        ___qtreewidgetitem24->setText(0, QApplication::translate("MainWindow", "1", 0));

        const bool __sortingEnabled3 = treeWidget_5->isSortingEnabled();
        treeWidget_5->setSortingEnabled(false);
        QTreeWidgetItem *___qtreewidgetitem25 = treeWidget_5->topLevelItem(0);
        ___qtreewidgetitem25->setText(1, QApplication::translate("MainWindow", "LGW", 0));
        ___qtreewidgetitem25->setText(0, QApplication::translate("MainWindow", "2", 0));
        QTreeWidgetItem *___qtreewidgetitem26 = ___qtreewidgetitem25->child(0);
        ___qtreewidgetitem26->setText(3, QApplication::translate("MainWindow", "AM", 0));
        ___qtreewidgetitem26->setText(2, QApplication::translate("MainWindow", "130.100", 0));
        ___qtreewidgetitem26->setText(1, QApplication::translate("MainWindow", "LGW ATIS", 0));
        ___qtreewidgetitem26->setText(0, QApplication::translate("MainWindow", "2.3", 0));
        QTreeWidgetItem *___qtreewidgetitem27 = ___qtreewidgetitem25->child(1);
        ___qtreewidgetitem27->setText(3, QApplication::translate("MainWindow", "AM", 0));
        ___qtreewidgetitem27->setText(2, QApplication::translate("MainWindow", "123.789", 0));
        ___qtreewidgetitem27->setText(1, QApplication::translate("MainWindow", "LGW Departures", 0));
        ___qtreewidgetitem27->setText(0, QApplication::translate("MainWindow", "2.2", 0));
        QTreeWidgetItem *___qtreewidgetitem28 = ___qtreewidgetitem25->child(2);
        ___qtreewidgetitem28->setText(3, QApplication::translate("MainWindow", "AM", 0));
        ___qtreewidgetitem28->setText(2, QApplication::translate("MainWindow", "121.600", 0));
        ___qtreewidgetitem28->setText(1, QApplication::translate("MainWindow", "LGW Tower", 0));
        ___qtreewidgetitem28->setText(0, QApplication::translate("MainWindow", "2.1", 0));
        QTreeWidgetItem *___qtreewidgetitem29 = treeWidget_5->topLevelItem(1);
        ___qtreewidgetitem29->setText(1, QApplication::translate("MainWindow", "LHR", 0));
        ___qtreewidgetitem29->setText(0, QApplication::translate("MainWindow", "1", 0));
        QTreeWidgetItem *___qtreewidgetitem30 = ___qtreewidgetitem29->child(0);
        ___qtreewidgetitem30->setText(3, QApplication::translate("MainWindow", "AM", 0));
        ___qtreewidgetitem30->setText(2, QApplication::translate("MainWindow", "120.450", 0));
        ___qtreewidgetitem30->setText(1, QApplication::translate("MainWindow", "LHR Approach", 0));
        ___qtreewidgetitem30->setText(0, QApplication::translate("MainWindow", "1.2", 0));
        QTreeWidgetItem *___qtreewidgetitem31 = ___qtreewidgetitem29->child(1);
        ___qtreewidgetitem31->setText(3, QApplication::translate("MainWindow", "AM", 0));
        ___qtreewidgetitem31->setText(2, QApplication::translate("MainWindow", "118.345", 0));
        ___qtreewidgetitem31->setText(1, QApplication::translate("MainWindow", "LHR Tower", 0));
        ___qtreewidgetitem31->setText(0, QApplication::translate("MainWindow", "1.1", 0));
        treeWidget_5->setSortingEnabled(__sortingEnabled3);

        toolBox->setItemText(toolBox->indexOf(page_2), QApplication::translate("MainWindow", "NDB Bookmarks", 0));
        menuOptions->setTitle(QApplication::translate("MainWindow", "Menu", 0));
        menuWindows->setTitle(QApplication::translate("MainWindow", "Windows", 0));
        lineEdit->setInputMask(QApplication::translate("MainWindow", "___.___.___.___", 0));
        label->setText(QApplication::translate("MainWindow", "Hostname", 0));
        label_2->setText(QApplication::translate("MainWindow", "Port", 0));
        lineEdit_2->setInputMask(QApplication::translate("MainWindow", "_____", 0));
        label_3->setText(QApplication::translate("MainWindow", "Hostname", 0));
        lineEdit_3->setInputMask(QString());
        lineEdit_3->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(rx1), QApplication::translate("MainWindow", "Rx 1", 0));
        lineEdit_4->setInputMask(QApplication::translate("MainWindow", "___.___.___.___", 0));
        label_4->setText(QApplication::translate("MainWindow", "Hostname", 0));
        label_5->setText(QApplication::translate("MainWindow", "Port", 0));
        lineEdit_5->setInputMask(QApplication::translate("MainWindow", "_____", 0));
        label_6->setText(QApplication::translate("MainWindow", "Hostname", 0));
        lineEdit_6->setInputMask(QString());
        lineEdit_6->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(rx2), QApplication::translate("MainWindow", "Rx 2", 0));
        lineEdit_7->setInputMask(QApplication::translate("MainWindow", "___.___.___.___", 0));
        label_7->setText(QApplication::translate("MainWindow", "Hostname", 0));
        label_8->setText(QApplication::translate("MainWindow", "Port", 0));
        lineEdit_8->setInputMask(QApplication::translate("MainWindow", "_____", 0));
        label_9->setText(QApplication::translate("MainWindow", "Hostname", 0));
        lineEdit_9->setInputMask(QString());
        lineEdit_9->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(rx3), QApplication::translate("MainWindow", "Rx 3", 0));
        lineEdit_19->setInputMask(QString());
        label_19->setText(QApplication::translate("MainWindow", "Mode", 0));
        label_20->setText(QApplication::translate("MainWindow", "Description", 0));
        lineEdit_20->setInputMask(QString());
        label_21->setText(QApplication::translate("MainWindow", "Frequency (Hz)", 0));
        lineEdit_21->setInputMask(QApplication::translate("MainWindow", "99999999999", 0));
        lineEdit_21->setText(QString());
        pushButton->setText(QApplication::translate("MainWindow", "Remove", 0));
        pushButton_2->setText(QApplication::translate("MainWindow", "Add", 0));
        pushButton_3->setText(QApplication::translate("MainWindow", "Recall", 0));
        pushButton_4->setText(QApplication::translate("MainWindow", "Set", 0));
        pushButton_5->setText(QApplication::translate("MainWindow", "Get", 0));
        tabWidget_2->setTabText(tabWidget_2->indexOf(rx1_3), QApplication::translate("MainWindow", "Rx 1", 0));
        pushButton_11->setText(QApplication::translate("MainWindow", "Add", 0));
        pushButton_12->setText(QApplication::translate("MainWindow", "Recall", 0));
        pushButton_13->setText(QApplication::translate("MainWindow", "Get", 0));
        pushButton_14->setText(QApplication::translate("MainWindow", "Remove", 0));
        lineEdit_22->setInputMask(QApplication::translate("MainWindow", "99999999999", 0));
        lineEdit_22->setText(QString());
        label_22->setText(QApplication::translate("MainWindow", "Mode", 0));
        pushButton_15->setText(QApplication::translate("MainWindow", "Set", 0));
        lineEdit_23->setInputMask(QString());
        label_23->setText(QApplication::translate("MainWindow", "Description", 0));
        label_24->setText(QApplication::translate("MainWindow", "Frequency (Hz)", 0));
        lineEdit_24->setInputMask(QString());
        tabWidget_2->setTabText(tabWidget_2->indexOf(rx2_3), QApplication::translate("MainWindow", "Rx 2", 0));
        pushButton_16->setText(QApplication::translate("MainWindow", "Add", 0));
        pushButton_17->setText(QApplication::translate("MainWindow", "Recall", 0));
        pushButton_18->setText(QApplication::translate("MainWindow", "Get", 0));
        pushButton_19->setText(QApplication::translate("MainWindow", "Remove", 0));
        lineEdit_25->setInputMask(QApplication::translate("MainWindow", "99999999999", 0));
        lineEdit_25->setText(QString());
        label_25->setText(QApplication::translate("MainWindow", "Mode", 0));
        pushButton_20->setText(QApplication::translate("MainWindow", "Set", 0));
        lineEdit_26->setInputMask(QString());
        label_26->setText(QApplication::translate("MainWindow", "Description", 0));
        label_27->setText(QApplication::translate("MainWindow", "Frequency (Hz)", 0));
        lineEdit_27->setInputMask(QString());
        tabWidget_2->setTabText(tabWidget_2->indexOf(rx3_3), QApplication::translate("MainWindow", "Rx 3", 0));
        label_55->setText(QApplication::translate("MainWindow", "Frequency Scanning", 0));
        label_10->setText(QApplication::translate("MainWindow", "Min", 0));
        label_11->setText(QApplication::translate("MainWindow", "Max", 0));
        label_12->setText(QApplication::translate("MainWindow", "Interval", 0));
        label_13->setText(QApplication::translate("MainWindow", "kHz", 0));
        label_14->setText(QApplication::translate("MainWindow", "kHz", 0));
        label_15->setText(QApplication::translate("MainWindow", "Scan mode", 0));
        radioButton->setText(QApplication::translate("MainWindow", "Auto Bookmark", 0));
        pushButton_6->setText(QApplication::translate("MainWindow", "Start", 0));
        label_56->setText(QApplication::translate("MainWindow", "Scanning options", 0));
        label_16->setText(QApplication::translate("MainWindow", "Signal Level", 0));
        label_17->setText(QApplication::translate("MainWindow", "dBFS", 0));
        label_18->setText(QApplication::translate("MainWindow", "Seconds", 0));
        label_28->setText(QApplication::translate("MainWindow", "Delay", 0));
        label_29->setText(QApplication::translate("MainWindow", "0 = infinite", 0));
        label_30->setText(QApplication::translate("MainWindow", "Passes", 0));
        radioButton_2->setText(QApplication::translate("MainWindow", "Wait", 0));
        radioButton_3->setText(QApplication::translate("MainWindow", "Record", 0));
        radioButton_4->setText(QApplication::translate("MainWindow", "Aggr", 0));
        radioButton_5->setText(QApplication::translate("MainWindow", "Log", 0));
        label_57->setText(QApplication::translate("MainWindow", "Bookmark Scanning", 0));
        pushButton_7->setText(QApplication::translate("MainWindow", "Start", 0));
        pushButton_8->setText(QApplication::translate("MainWindow", "Lock", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
